version: '3.7'
services:
  postgres:
    container_name: postgres-container-demo
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PREMIERE
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
volumes:
  postgres:
  postgresql_data:
    driver: local